name: "Bug Report"
description: Create a new ticket for a bug.
title: "<title>"
labels: [
  "Type: Bug"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please enter an explicit description of your issue
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      value: |
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: bash
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: "Version"
      description: What version of our software are you running?
      options:
        - Release (downloaded from Docker Hub)
        - Release (self built from "release" branch)
        - Latest (downloaded from Docker Hub with latest tag)
        - Latest (self built from "main" branch)
        - Dev (built with docker from any other branch)
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: Please enter a detailed description of your environment.
      placeholder: Include OS name and version, browser name and version, docker and compose plugin version, and other useful information...
    validations:
      required: true
